import {Nunito} from "next/font/google";
import "./globals.css";

const er = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
         className={er.className}
      >
        {children}
      </body>
    </html>
  );
}
